use chatdb;

CREATE TABLE TBL_CHAT (
	CHAT_NO INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL
);

SELECT * FROM TBL_CHAT;

DROP TABLE IF EXISTS CREW_BOARD CASCADE;

CREATE TABLE CREW_BOARD (
	POST_NO INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CREW_NO INT,
    USER_NO INT NOT NULL,
    POST_DATE TIMESTAMP,
    POST_TITLE VARCHAR(200) NOT NULL,
    POST_CONTENT VARCHAR(200) NOT NULL,
    POST_STATUS CHAR(1) DEFAULT 'Y'
);
    
SELECT * FROM CREW_BOARD;

INSERT INTO CREW_BOARD
	VALUES
    (NULL, 2, 3, NOW(), "첫번째 게시글", "첫번째 내용~~~~~", DEFAULT),
    (NULL, 3, 4, NOW(), "두번째 게시글", "두번째 내용~~~~~", DEFAULT),
	(NULL, 4, 5, NOW(), "세번째 게시글", "세번째 내용~~~~~", DEFAULT);
    
DROP TABLE IF EXISTS TBL_USER CASCADE;
CREATE TABLE TBL_USER (
	USER_CODE INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    USER_PWD VARCHAR(100) NOT NULL,
    NICKNAME VARCHAR(100) NOT NULL,
    PROFILE_IMG VARCHAR(255) NOT NULL,
    USER_ROLE VARCHAR(50) NOT NULL
) ENGINE=INNODB;

DROP TABLE IF EXISTS TBL_USER_RELATION CASCADE;
CREATE TABLE BL_USER_RELATION (
	USER_CODE INT 
	REVIEW_CODE INT 
) ENGINE=INNODB;
	